### ISSUE TITLE
How can I change the style to circle not straight?

### ISSUE THREAD

**Issue by deepakrnan** [MarioIannotta/MIFab#2]
Hi,

Thanks you, Good work!!!!

I don't how to make the straight action to circular action. Is there any possibility to do. I searched but found nothing.

Please help me....

Thank you once again...

**Comment by MarioIannotta** [comment]
Hi Deepakrnan, 
if I understood you want to change the borderRadius of the buttons; right now you can't do that from "outside" the library but you have to edit the line 34 of `MIFabOptionCell.swift`.

I'll try to update the repository to add the feature you're asking.

**Comment by deepakrnan** [comment]
Hi MarioIannotta,

Thanks for the response...

No am just asking like in https://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2016/01/1453283451Screenshot.png

But with the Label. Is that possible now.

Thank You once again...

**Comment by MarioIannotta** [comment]
Ohh I see, I'm sorry but this is not possible.
